---
title: "About Me"
toc: true
---

## Education

**PhD in Psychology** \| National University of Singapore\
Aug 2021 - Nov 2025

**B.Soc.Sc in Psychology with Honours (Highest Distinction)** \| Nanyang Technological University\
Aug 2017 - May 2021

## Research Topics of Interest

-   Treatment adherence
-   Network approach to mental disorders
-   Network psychometrics
-   Developing and evaluating mHealth interventions
-   Open science

## Research Experience

**Graduate Research Assistant**\
Sung Lab, Duke-NUS Medical School\
Jan 2025 - Present

**Graduate Research Assistant**\
[A/Prof Bibhas Chakraborty's Research Lab](https://blog.nus.edu.sg/bibhas/), Duke-NUS Medical School\
Sep 2021 - Aug 2024

**Graduate Research Assistant**\
Personality & Psychopathology Lab, National University of Singapore\
Jun 2022 - Dec 2022

**Associate Clinical Research Coordinator**\
Department of Psychology, Singapore General Hospital\
Jan 2021 - Jun 2021

**Clinical Research Intern**\
Department of Psychology, Singapore General Hospital\
Mar 2019 - Dec 2020

**Student Researcher**\
NTU Touch Lab, Nanyang Technological University (now the [Kobe Multisensory Lab](https://touchlab.mystrikingly.com/))\
Aug 2018 - Jun 2019

## Teaching Experience

**Teaching Assistant**\
Networks in Psychology (PL4246)\
Department of Psychology, National University of Singapore\
Semester 1, AY24/25

**Teaching Assistant**\
Introduction to Clinical Psychology (PL3257)\
Department of Psychology, National University of Singapore\
Semester 1, AY22/23

**Teaching Assistant**\
Abnormal Psychology (PL3106)\
Department of Psychology, National University of Singapore\
Semester 2, AY21/22

**Teaching Assistant**\
Biological Psychology (PL3102)\
Department of Psychology, National University of Singapore\
Semester 1, AY21/22
