---
title: "Research"
toc: true
---

My Google Scholar profile can be found [here](https://scholar.google.com.sg/citations?user=P9Tl79kAAAAJ&hl=en). In the spirit of open science, where available, each publication's corresponding OSF project page will be linked below.

## Journal Articles

Pasqualotto, A., **Leong, U.**, & Kitada, R. (2025). Touching soft materials slows affective visual processing. *Frontiers in Psychology*, *16*, 1644393. https://doi.org/10.3389/fpsyg.2025.1644393

Zainal, N. H., Liu, X., **Leong, U.**, Yan, X., & Chakraborty, B. (2025). Bridging Innovation and Equity: Advancing Public Health Through Just-in-Time Adaptive Interventions. *Annual Review of Public Health*, *46*(1), 43–68. <https://doi.org/10.1146/annurev-publhealth-071723-103909>

**Leong, U.**, Epskamp, S., Isvoranu, A.-M., Angulo-Brunet, A., & Hong, R. Y. (2025). Associations Between a Transdiagnostic Core Vulnerability and Internalizing Symptoms: A Network Analysis. *Cognitive Therapy and Research*, *49*(2), 291–301. <https://doi.org/10.1007/s10608-024-10524-7> [\[OSF\]](https://osf.io/z5t8d/)

**Leong, U.**, & Chakraborty, B. (2023). Participant Engagement in Microrandomized Trials of mHealth Interventions: Scoping Review. *JMIR MHealth and UHealth*, *11*, e44685. <https://doi.org/10.2196/44685> [\[OSF\]](https://osf.io/xdnr8/)

## Registered Reports

**Leong, U.**, Chan, E. H. L., Yau, W. T., Ng, W. Y., Chim, T. W., Yeung, W., Tam, K. Y. Y., & Feldman, G. (2024). On the moralization of vegetarianism and differences between health and moral vegetarians: Registered Report replicating and extending Rozin et al. (1997) \[Stage 1\]. *Open Science Framework*. <https://osf.io/rac6q> [\[Stage 1 in-principle acceptance\]](https://rr.peercommunityin.org/articles/rec?id=898) [\[OSF\]](https://osf.io/5azdg)

## Preprints

**Leong, U**., Seah, F. E., Epskamp, S., Zainal, N., & Hong, R. Y. (2025). Investigating the Associations among Core Cognitive Vulnerability, Internalizing Symptoms, and Negative Situational Experiences: A Longitudinal Network Analysis. *PsyArXiv*. <https://doi.org/10.31234/osf.io/2xey7_v1> [\[OSF\]](https://osf.io/qm4xs/)

<!-- **Leong, U.**, Epskamp, S., Isvoranu, A., Angulo-Brunet, A., & Hong, R. Y. (2024). Associations Between a Transdiagnostic Core Vulnerability and Internalizing Symptoms: A Network Analysis. *PsyArXiv*. <https://doi.org/10.31234/osf.io/cwd46> -->

## Conference Presentations

Presenting authors are underlined. Conference presentation materials can be found [here](https://osf.io/rju35/).

<u>**Leong, U.**</u>, Epskamp, S., Isvoranu, A., Angulo-Brunet, A., & Hong, R. Y. (2024, July 21-26). Associations Between a Transdiagnostic Core Vulnerability and Internalizing Symptoms: A Network Analysis \[Poster presentation\]. 33rd International Congress of Psychology, Prague, Czech Republic.

<u>Henderson, S. L.</u>, Sugumar, L., **Leong, U.**, & Doshi, K. (2020, November 5-8). Evaluating mindfulness self-report questionnaires for scale development in a Singapore context: A focus group discussion \[Conference presentation\]. The Mind & Life 2020 Contemplative Research Conference, Singapore.
